#!/bin/sh

### Work in the Conda_env_ChIP_processing environment
# The file ./scaling-factors_list.tsv  must be present in the same directory as this Script

#provide the paired IP and Input samples
IPs=("JS43" "JS49")
INs=("JS46" "JS52")

### all the bam files generated by the first Script Script_ssChIP_from_reads_to_bam_and_calibrated_bw.sh must be  moved to the same folder
inputdir='/mnt/e/Science/ChIP/bam/'
cores=6
binning=100 #size of the binning to compute FWD/REV ratio


### if not done before, create a tracks folder to store the coverage tracks
# mkdir ./ChIP-seq/tracks/
# mkdir ./ChIP-seq/tracks/calibrated_filtered_smoothed/
# mkdir ./ChIP-seq/tracks/calibrated_filtered_smoothed/bedgraph


now=$(date +"%Y-%m-%d %H:%M:%S")
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> New run of the script: $now" >> 20260303_calibrated_coverage_computation.log

for ((i = 0; i < ${#IPs[@]}; i++)); do
    IP="${IPs[$i]}"
    IN="${INs[$i]}"

    bamIP=$(ls $inputdir | grep "$IP" | grep "unmapped_GCF" | grep ".bam$")
    bamIN=$(ls $inputdir | grep "$IN" | grep "unmapped_GCF" | grep ".bam$")
    scalefactor=$(cat ./scaling-factors_list.tsv | grep "$IP" | cut -f 2) # recovery of the corresponding scale factor

    echo $bamIP
    echo $bamIN
    echo $scalefactor

    ### for the history log
    echo $bamIP >> 20251021_calibrated_coverage_computation.log
    echo $bamIN >> 20251021_calibrated_coverage_computation.log
    echo $scalefactor >> 20251021_calibrated_coverage_computation.log

    ###### JUST BINNED BUT NO CALIBRATION

    out_fwd=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD.CPM.$binning""bp-binning.bw,"`
    #out_fwd_bed=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/bedgraph/,' | sed "s,.bam,.FWD.CPM.$binning""bp-binning.bedgraph,"`
    out_rev=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.REV.CPM.$binning""bp-binning.bw,"`
    #out_rev_bed=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/bedgraph/,' | sed "s,.bam,.REV.CPM.$binning""bp-binning.bedgraph,"`
    # out_ratio=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD-vs-REV.$binning""bp-binning.bw,"`
    #out_ratio=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD-vs-REV.5bp-binning.bw,"`
    #out_ratio_pseudocount_5=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD-vs-REV.pseudocount.5bp-binning.bw,"`
    out_ratio_pseudocount=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD-vs-REV.pseudocount.$binning""bp-binning.bw,"`
    #out_IPvsIN_bw=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.$IP-vs-$IN.$binning""bp-binning.bw,"`
    #out_IPvsIN_bed=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/bedgraph/,' | sed "s,.bam,.$IP-vs-$IN.$binning""bp-binning.bedgraph,"`

    #out_input_fwd=`echo "$inputdir/$bamIN" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD.CPM.$binning""bp-binning.bw,"`
    #out_input_rev=`echo "$inputdir/$bamIN" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.REV.CPM.$binning""bp-binning.bw,"`
    #out_input_ratio=`echo "$inputdir/$bamIN" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD-vs-REV.5bp-binning.bw,"`

    bamCoverage \
        --bam "$inputdir/$bamIP" \
        --outFileName "${out_fwd}" \
        --outFileFormat "bigwig" \
        --binSize $binning \
        --numberOfProcessors $cores \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates \
        --filterRNAstrand reverse
    bamCoverage \
        --bam "$inputdir/$bamIP" \
        --outFileName "${out_rev}" \
        --outFileFormat "bigwig" \
        --binSize $binning \
        --numberOfProcessors $cores \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates \
        --filterRNAstrand forward
    #bamCoverage \
    #    --bam "$inputdir/$bamIN" \
    #    --outFileName "${out_input_fwd}" \
    #    --outFileFormat "bigwig" \
    #    --binSize $binning \
    #    --numberOfProcessors $cores \
    #    --normalizeUsing CPM \
    #    --skipNonCoveredRegions \
    #    --extendReads \
    #    --ignoreDuplicates \
    #    --filterRNAstrand reverse

    #bamCoverage \
    #    --bam "$inputdir/$bamIN" \
    #    --outFileName "${out_input_rev}" \
    #    --outFileFormat "bigwig" \
    #    --binSize $binning \
    #    --numberOfProcessors $cores \
    #    --normalizeUsing CPM \
    #    --skipNonCoveredRegions \
    #    --extendReads \
    #    --ignoreDuplicates \
    #    --filterRNAstrand forward

    #bamCoverage \
    #    --bam "$inputdir/$bamIP" \
    #    --outFileName "${out_fwd_bed}" \
    #    --outFileFormat "bedgraph" \
    #    --binSize $binning \
    #    --numberOfProcessors $cores \
    #    --normalizeUsing CPM \
    #    --skipNonCoveredRegions \
    #    --extendReads \
    #    --ignoreDuplicates \
    #    --filterRNAstrand reverse

    #bamCoverage \
    #    --bam "$inputdir/$bamIP" \
    #    --outFileName "${out_rev_bed}" \
    #    --outFileFormat "bedgraph" \
    #    --binSize $binning \
    #    --numberOfProcessors $cores \
    #    --normalizeUsing CPM \
    #    --skipNonCoveredRegions \
    #    --extendReads \
    #    --ignoreDuplicates \
    #    --filterRNAstrand forward
    
    #bamCompare \
    #    -b1 "$inputdir/$bamIP" \
    #    -b2 "$inputdir/$bamIN" \
    #    -o "${out_IPvsIN_bw}" \
    #    -of "bigwig" \
    #    --operation "ratio" \
    #    --skipZeroOverZero \
    #    -bs $binning \
    #    -p $cores \
    #    --normalizeUsing "CPM" \
    #    --scaleFactorsMethod None \
    #    --skipNonCoveredRegions \
    #    --extendReads \
    #    --ignoreDuplicates

    #bamCompare \
    #    -b1 "$inputdir/$bamIP" \
    #    -b2 "$inputdir/$bamIN" \
    #    -o "${out_IPvsIN_bed}" \
    #    -of "bedgraph" \
    #    --operation "ratio" \
    #    --skipZeroOverZero \
    #    -bs $binning \
    #    -p $cores \
    #    --normalizeUsing "CPM" \
    #    --scaleFactorsMethod None \
    #    --skipNonCoveredRegions \
    #    --extendReads \
    #    --ignoreDuplicates        

    #bigwigCompare \
    #    --binSize 5 \
    #    --numberOfProcessors $cores \
    #    --outFileName "${out_ratio}" \
    #    --bigwig1 "${out_fwd}" \
    #    --bigwig2 "${out_rev}" \
    #    --skipZeroOverZero \
    #    --operation "log2" \
    #    --skipNonCoveredRegions

    #bigwigCompare \
    #    --binSize 5 \
    #    --numberOfProcessors $cores \
    #    --outFileName "${out_input_ratio}" \
    #    --bigwig1 "${out_input_fwd}" \
    #    --bigwig2 "${out_input_rev}" \
    #    --skipZeroOverZero \
    #    --operation "log2" \
    #    --skipNonCoveredRegions

    #bigwigCompare \
    #    --binSize 5 \
    #    --numberOfProcessors $cores \
    #    --outFileName "${out_ratio_pseudocount_5}" \
    #    --bigwig1 "${out_fwd}" \
    #    --bigwig2 "${out_rev}" \
    #    --skipZeroOverZero \
    #    --pseudocount 1 \
    #    --operation "log2" \
    #    --skipNonCoveredRegions

    bigwigCompare \
        --binSize $binning \
        --numberOfProcessors $cores \
        --outFileName "${out_ratio_pseudocount}" \
        --bigwig1 "${out_fwd}" \
        --bigwig2 "${out_rev}" \
        --skipZeroOverZero \
        --pseudocount 1 \
        --operation "log2" \
        --skipNonCoveredRegions
    
    ###### SAME ANALYSIS BUT WITH SCALING FACTOR (CALIBRATION)
    ### to run that part of the code you need a list of scaling factors (for each IP-IN combination) that are computed in tinymapper and stored in a stats folder
    
    ### calibrated IP
    out_cal_bw=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/,' | sed "s,.bam,.CPM.$binning""bp-binning.calibrated.bw,"`
    
    bamCoverage \
        --bam "$inputdir/$bamIP" \
        --outFileName "${out_cal_bw}" \
        --outFileFormat "bigwig" \
        --binSize $binning \
        --scaleFactor $scalefactor \
        --numberOfProcessors $cores \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates
    
    ### calibrated input
    out_cal_input_bw=`echo "$inputdir/$bamIN" | sed 's,bam/,tracks/,' | sed "s,.bam,.CPM.$binning""bp-binning.calibrated.bw,"`
    
    bamCoverage \
        --bam "$inputdir/$bamIN" \
        --outFileName "${out_cal_input_bw}" \
        --outFileFormat "bigwig" \
        --binSize $binning \
        --scaleFactor $scalefactor \
        --numberOfProcessors $cores \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates    
    
    ### calibrated IP with split fwd and rev reads (bigwig format)
    out_cal_fwd_bw=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.FWD.CPM.$binning""bp-binning.calibrated.bw,"`
    out_cal_rev_bw=`echo "$inputdir/$bamIP" | sed 's,bam/,tracks/calibrated_filtered_smoothed/,' | sed "s,.bam,.REV.CPM.$binning""bp-binning.calibrated.bw,"`
    
    bamCoverage \
        --bam "$inputdir/$bamIP" \
        --outFileName "${out_cal_fwd_bw}" \
        --outFileFormat "bigwig" \
        --binSize $binning \
        --scaleFactor $scalefactor \
        --numberOfProcessors $cores \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates \
        --filterRNAstrand reverse
    bamCoverage \
        --bam "$inputdir/$bamIP" \
        --outFileName "${out_cal_rev_bw}" \
        --outFileFormat "bigwig" \
        --binSize $binning \
        --scaleFactor $scalefactor \
        --numberOfProcessors $cores \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates \
        --filterRNAstrand forward
    



done